services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: product_order
      POSTGRES_PASSWORD: product_order
      POSTGRES_DB: product_order
    ports:
      - "25432:5432"
    volumes:
      - product_order_data:/var/lib/postgresql/data

volumes:
  product_order_data: