services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: product_order
      POSTGRES_PASSWORD: product_order
      POSTGRES_DB: product_order
    ports:
      - "25432:5432"
    volumes:
      - product_order_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "26379:6379"
    volumes:
      - redis_data:/data

volumes:
  product_order_data:
  redis_data:
